FROM alpine

#RUN set -x ; \
#  addgroup -g 82 -S www-data ; \
#  adduser -u 82 -D -S -G www-data www-data && exit 0 ; exit 1

RUN apk add  \
    php  \
    php-fpm  \
    nginx  \
    php-ctype \
    php-dom \
    php-tokenizer \
    php-session \
    php-gd \
    php-pdo_mysql \
    php83-mysqlnd \
    php83-mysqli \
    php-openssl \
    freetype \
    composer \
    supervisor \
    php-xml \
    php-simplexml \
    opensmtpd \
    php-pecl-redis \
    php-pecl-memcached \
    php-pecl-memcache \
    php-zip \
    php-xmlwriter \
    php-xml \
    php83-fileinfo \
    npm

COPY . /app
COPY ./.docker/nginx.conf /etc/nginx/nginx.conf
COPY ./.docker/php.ini /etc/php83/php.ini
COPY ./.docker/php-fpm.conf /etc/php83/php-fpm.conf

COPY ./.docker/entrypoint.sh entrypoint.sh
RUN chmod 777 entrypoint.sh

CMD ["./entrypoint.sh"]
EXPOSE 8081