<?php

namespace ContainerGgPdlI9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebPageParserControllerparseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7XSqXTK.App\Controller\WebPageParserController::parse()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7XSqXTK.App\\Controller\\WebPageParserController::parse()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'DBpersister' => ['privates', 'App\\Parser\\DBpersister', 'getDBpersisterService', true],
        ], [
            'DBpersister' => 'App\\Parser\\DBpersister',
        ]))->withContext('App\\Controller\\WebPageParserController::parse()', $container);
    }
}
